kind: pipeline
name: drone-with-go
type: docker

steps:
  - name: tests
    image: golang:latest
    commands:
      - go env -w GO111MODULE=auto
      - go vet
      - go test -v -cover
    when:
      event:
        - pull_request
  - name: build
    image: golang:latest
    commands:
      - go env -w GO111MODULE=auto
      - go build
    when:
      branch:
        - master
      event:
        - push
